version: "3.8"

services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator
    container_name: spanner-emulator
    ports:
      - "9010:9010"  # gRPC
      - "9020:9020"  # REST
    environment:
      - SPANNER_EMULATOR_HOST=0.0.0.0:9010
    restart: unless-stopped
